const toast = document.getElementById('toast');
const showToast = (msg) => { toast.textContent = msg; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); };
const transcript = document.getElementById('transcript');
const handoff = document.getElementById('handoffCard');
const statePill = document.getElementById('statePill');
const signalValue = document.getElementById('signalValue');
const statusText = document.getElementById('statusText');
const customerMeta = document.getElementById('customerMeta');
let escalated = false;
let consented = false;
let browserRecognition;
let activeLeadProfile={last_completed:'postcode',intent:'complete Energy comparison',missing:['move-in date','NMI','usage','solar','contact'],consent:true};
let activeLeadId='EN-48219';
const leadProfiles={
  'EN-48219':{last_completed:'postcode',intent:'moving home',missing:['move-in date','NMI','usage','solar','contact'],consent:true,fieldKeys:['nmi','usage','household','solar','controlled','ev','contactName','contactEmail','contactPhone','concession']},
  'EN-48207':{last_completed:'usage estimate',intent:'find a cheaper plan',missing:['solar','EV','contact'],consent:true,fieldKeys:['solar','ev','contactName','contactEmail','contactPhone']},
  'EN-48188':{last_completed:'retailer',intent:'save current quote',missing:['contact','consent'],consent:false,fieldKeys:['contactName','contactEmail','contactPhone','concession']},
  'EN-48164':{last_completed:'postcode',intent:'new connection',missing:['move-in date','NMI','usage','solar','contact'],consent:true,fieldKeys:['nmi','usage','household','solar','controlled','ev','contactName','contactEmail','contactPhone','concession']}
};
let journeyState = 'consent';
const advancedFields = ['nmi','usage','household','solar','controlled','ev','contactName','contactEmail','contactPhone','concession'];
const advancedQuestions = ['What is your 11-digit NMI?','Do you have a recent bill or smart-meter usage data?','How many people live in the household?','Do you have solar panels? If yes, what size?','Do you have a controlled-load meter?','Do you have an electric vehicle?','What name should we use for this test comparison?','What test email should we use?','What test phone number should we use?','Do you hold a Pensioner Concession Card or Health Care Card?'];
let advancedIndex = 0;
const extraLeads = [
  ['Arjun Mehta','AM','coral','Postcode','HIGH','Call now'],['Sofia Rossi','SR','blue','Move-in date','MED','Send reminder'],['Noah Williams','NW','mint','Retailer','READY','Continue'],['Emily Chen','EC','violet','Usage estimate','READY','Continue'],['Oliver Smith','OS','blue','Postcode','READY','Call today'],['Grace Lee','GL','coral','Move-in date','MED','Send reminder'],['Ethan Brown','EB','mint','Retailer','READY','Continue'],['Ava Martin','AM','violet','Postcode','READY','Call today'],['William Jones','WJ','blue','Usage estimate','READY','Continue'],['Isla Taylor','IT','coral','Retailer','REVIEW','Check DNC'],['Jack Wilson','JW','mint','Postcode','READY','Call today'],['Mia Davis','MD','violet','Move-in date','READY','Continue'],['Leo Anderson','LA','blue','Retailer','READY','Continue'],['Ruby Thomas','RT','coral','Postcode','MED','Send reminder'],['Henry Moore','HM','mint','Usage estimate','READY','Continue'],['Chloe Jackson','CJ','violet','Move-in date','REVIEW','Check DNC'],['Charlie White','CW','blue','Retailer','READY','Continue'],['Ella Harris','EH','coral','Postcode','READY','Call today'],['James Clark','JC','mint','Usage estimate','READY','Continue'],['Amelia Lewis','AL','violet','Retailer','READY','Continue']
];
const leadList = document.querySelector('.lead-list');
extraLeads.forEach(([name, initials, color, field, priority, action], i) => { const b=document.createElement('button'); b.className='lead'; b.dataset.name=name; b.dataset.id=`EN-${48100-i}`; b.innerHTML=`<span class="avatar ${color}">${initials}</span><span class="lead-info"><strong>${name} <em class="priority ${priority==='HIGH'?'high':priority==='MED'?'medium':priority==='REVIEW'?'review':''}">${priority}</em></strong><small>${field} · ${i+1}d ago</small><small class="action">${action} · ${priority==='HIGH'?'84':priority==='MED'?'61':'72'}% likely</small></span><span class="lead-chevron">›</span>`; leadList.appendChild(b); b.addEventListener('click',()=>{document.querySelectorAll('.lead').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('customerName').innerHTML=`${name} <span class="verified">✓</span>`;document.getElementById('customerMeta').textContent=`Lead ${b.dataset.id} · Energy comparison · 1 field remaining`;showToast(`Loaded ${name}'s recovery journey`)}); });
const greeting = "Hi Priya, I’m Auralis calling from the Energy comparison team. This call is recorded for quality and safety. Is now a good time to continue your comparison? You can ask for a human at any time.";
function speakAuralis(text){ const u=new SpeechSynthesisUtterance(text); const voices=window.speechSynthesis.getVoices(); const preferred=voices.find(v=>/female|samantha|victoria|karen|zira|google uk english female|susan/i.test(v.name)); if(preferred)u.voice=preferred; u.lang='en-AU'; u.rate=.96; u.pitch=1.12; window.speechSynthesis.speak(u); }
window.speechSynthesis.onvoiceschanged=()=>{};
const nativeSpeechSpeak=window.speechSynthesis.speak.bind(window.speechSynthesis); window.speechSynthesis.speak=(utterance)=>{ const voices=window.speechSynthesis.getVoices(); const preferred=voices.find(v=>/female|samantha|victoria|karen|zira|google uk english female|susan/i.test(v.name)); if(preferred) utterance.voice=preferred; utterance.lang='en-AU'; utterance.pitch=1.12; utterance.rate=.96; const oldEnd=utterance.onend; utterance.onend=(event)=>{ if(oldEnd) oldEnd(event); setTimeout(()=>{if(browserRecognition&&journeyState!=='ended'&&journeyState!=='handoff'){try{browserRecognition.start()}catch(_){}}},500); }; nativeSpeechSpeak(utterance); };
document.getElementById('startBtn').addEventListener('click', () => {
  const profile=activeLeadProfile; const personalized=profile.last_completed==='postcode'?greeting.replace('continue your comparison','continue from the postcode step'):profile.last_completed==='usage estimate'?"Hi, this is Auralis. This call is recorded for quality and safety. Your usage estimate is already saved, so I’ll only ask about the remaining solar, EV, and contact details. Is now a good time?":"Hi, this is Auralis. This call is recorded for quality and safety. I can see your Energy comparison is nearly complete. May I confirm the remaining details?";
  transcript.innerHTML = `<div class="turn ai"><span class="turn-label">AURALIS · NOW</span><p>${personalized}</p></div>`;
  statusText.textContent = 'Awaiting consent'; customerMeta.textContent = `Lead ${activeLeadId} · Energy comparison · Awaiting consent`;
  window.speechSynthesis.cancel(); const greetingUtterance=new SpeechSynthesisUtterance(personalized); greetingUtterance.onend=()=>setTimeout(()=>{if(browserRecognition){try{browserRecognition.start()}catch(_){}}},400); window.speechSynthesis.speak(greetingUtterance);
  showToast('Call started — consent is required before collecting details.');
  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  if (SpeechRecognition) { browserRecognition = new SpeechRecognition(); browserRecognition.lang='en-AU'; browserRecognition.continuous=false; browserRecognition.interimResults=false; browserRecognition.maxAlternatives=1; browserRecognition.onresult=e=>{const phrase=e.results[e.resultIndex]?.[0]?.transcript?.trim(); if(phrase) sendChat(phrase)}; browserRecognition.onerror=()=>{}; browserRecognition.onend=()=>{setTimeout(()=>{if(browserRecognition&&journeyState!=='ended'&&journeyState!=='handoff'){try{browserRecognition.start()}catch(_){}}},700)}; }
});

document.querySelectorAll('.lead').forEach((lead) => lead.addEventListener('click', () => {
  document.querySelectorAll('.lead').forEach(x => x.classList.remove('active')); lead.classList.add('active');
  document.getElementById('customerName').innerHTML = `${lead.dataset.name} <span class="verified">✓</span>`;
  customerMeta.textContent = `Lead ${lead.dataset.id} · Energy comparison · 1 field remaining`;
  showToast(`Loaded ${lead.dataset.name}'s recovery journey`);
}));

function runFrustration() {
  if (escalated) return;
  const complaint = "I've already told three of you my details. I'm done with this — stop calling me.";
  const turn = document.createElement('div'); turn.className = 'turn customer'; turn.innerHTML = `<span class="turn-label">${activeLeadId} · NOW</span><p class="highlight" style="background:#fff0ec;color:#a94e40">${complaint}</p>`;
  transcript.appendChild(turn); transcript.scrollTop = transcript.scrollHeight;
  fetch('http://localhost:8000/api/conversation/analyse', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({lead_id:activeLeadId, text:complaint})}).catch(()=>null);
  setTimeout(() => {
    const ai = document.createElement('div'); ai.className = 'turn ai'; ai.innerHTML = '<span class="turn-label">AURALIS · NOW</span><p>I hear you. I\'ll stop the automated call now and connect you with a person so you don\'t have to repeat anything.</p>'; transcript.appendChild(ai); transcript.scrollTop = transcript.scrollHeight;
    escalated = true; statePill.textContent = 'HANDOFF NOW'; statePill.className = 'state-pill alert'; signalValue.textContent = 'Frustration / DNC request'; statusText.textContent = 'Human handoff'; handoff.classList.add('alert'); handoff.querySelector('strong').textContent = 'HANDOFF IN PROGRESS'; handoff.querySelector('p').textContent = 'Reason: explicit do-not-call request · context attached'; customerMeta.textContent = `Lead ${activeLeadId} · Escalating with context`;
    fetch('http://localhost:8000/api/handoff', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({lead_id:activeLeadId, text:complaint})}).catch(()=>null);
    showToast('Safety boundary triggered — human handoff created');
  }, 650);
}
document.getElementById('frustrationBtn').addEventListener('click', runFrustration);
function saveTurn(role, text) { const key=`auralis-conversation-${activeLeadId}`; const turns=JSON.parse(localStorage.getItem(key)||'[]'); turns.push({role,text,timestamp:new Date().toISOString()}); localStorage.setItem(key, JSON.stringify(turns)); if(typeof notes!=='undefined' && role==='customer' && notes){ const compact=text.length>140?text.slice(0,140)+'…':text; notes.value+=(notes.value?'\n':'')+`• Customer: ${compact}`; localStorage.setItem(notesKey(),notes.value); } fetch(`http://localhost:8000/api/conversations/${activeLeadId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,text})}).catch(()=>{}); }
async function sendChat(text) {
  if (!text.trim()) return;
  if (journeyState==='handoff' || journeyState==='ended') return;
  if (journeyState==='complete') { showToast('Journey already submitted — no further questions.'); return; }
  const turn=document.createElement('div'); turn.className='turn customer'; turn.innerHTML=`<span class="turn-label">CUSTOMER · NOW</span><p class="highlight">${text}</p>`; transcript.appendChild(turn); saveTurn('customer', text);
  const immediateSafety = text.toLowerCase();
  if (/don't have time|do not have time|dont have time|call me later|call later|call me sometime|some time later|busy right now|not a good time/.test(immediateSafety)) { const reply='Of course. I’ll end this call now and mark a callback for later. You won’t need to repeat the details you have already shared.'; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${reply}</p>`; transcript.appendChild(ai); saveTurn('assistant',reply); window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); journeyState='ended'; document.getElementById('statusText').textContent='Callback requested'; document.getElementById('nextActionValue').textContent='CALL BACK LATER'; document.getElementById('nextActionDetail').textContent='Customer unavailable now · details saved'; document.getElementById('signalValue').textContent='Callback requested'; document.getElementById('statePill').textContent='CALLBACK'; document.getElementById('statePill').className='state-pill'; showToast('Call ended — callback requested'); if(browserRecognition) browserRecognition.stop(); return; }
  if (/told you all|told you everything|three times|why are you calling|why do you keep|this is ridiculous|i am done|i'm done|i don't understand|i do not understand|i'm confused|i am confused|what are you asking|say that again|repeat that|not making sense/.test(immediateSafety)) { runFrustration(); return; }
  if (/stop calling|dont call|don't call|do not call|call me again|do not contact|i want a human|speak to a person|already told|leave me alone|i don't want to talk|i do not want to talk|dont want to talk|customer care/.test(immediateSafety)) { const reply='I understand. I’ll stop the automated call now and connect you with a human. You won’t need to repeat anything.'; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${reply}</p>`; transcript.appendChild(ai); saveTurn('assistant',reply); window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); statePill.textContent='HANDOFF NOW'; statePill.className='state-pill alert'; signalValue.textContent='Human request / DNC'; handoff.classList.add('alert'); handoff.querySelector('strong').textContent='HUMAN HANDOFF REQUIRED'; handoff.querySelector('p').textContent='Internal reason: DNC, frustration or human request · full context attached'; document.getElementById('statusText').textContent='Transferring to human'; document.getElementById('customerMeta').textContent=`Lead ${activeLeadId} · Handoff in progress`; showToast('Stopping automation — transferring to a human'); if(browserRecognition) browserRecognition.stop(); journeyState='handoff'; return; }
  if (journeyState==='privacy') { const answer=text.toLowerCase(); if(/no|decline|don't|do not/.test(answer)){ const reply='No problem, thank you for your time. I will not submit the comparison or contact you again. Your journey is saved as incomplete.'; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${reply}</p>`; transcript.appendChild(ai); saveTurn('assistant',reply); window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); document.getElementById('statusText').textContent='Journey incomplete · consent declined'; document.getElementById('customerMeta').textContent='Lead EN-48219 · Energy comparison · Consent declined'; document.getElementById('nextActionValue').textContent='DO NOT CONTACT'; document.getElementById('nextActionDetail').textContent='Customer declined consent · no submission'; showToast('Consent declined — journey saved incomplete'); journeyState='ended'; } else if(/yes|agree|consent|okay|ok/.test(answer)) { document.getElementById('privacyConsent').checked=true; document.getElementById('submitJourney').click(); const reply='Thank you. I have captured the complete Energy profile and submitted the test journey.'; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${reply}</p>`; transcript.appendChild(ai); saveTurn('assistant',reply); window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); journeyState='complete'; } return; }
  if (journeyState==='nmi' || journeyState==='advanced') { journeyState='advanced'; const fieldList=activeLeadProfile.fieldKeys||advancedFields; const field=fieldList[advancedIndex]; const el=document.getElementById(field); const unknown=/don't know|do not know|not sure|don't have|cannot remember|can't remember|no nmi/i.test(text); if(field==='nmi'&&!unknown&&!/\d{11}/.test(text.replace(/\D/g,''))){ const q='I could not verify an 11-digit NMI. You can say “I don’t know” and we will continue, or provide the number.'; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${q}</p>`; transcript.appendChild(ai); saveTurn('assistant',q); window.speechSynthesis.speak(new SpeechSynthesisUtterance(q)); return; } if(el){ if(unknown && field==='nmi'){el.value='Not provided';} else if(el.tagName==='SELECT'){ const option=[...el.options].find(o=>text.toLowerCase().includes(o.text.toLowerCase().split(' · ')[0].toLowerCase())); el.value=option?option.value:el.options[1]?.value||''; } else el.value=text; } advancedIndex++; if(advancedIndex<fieldList.length){ const nextField=fieldList[advancedIndex]; const q=unknown&&field==='nmi'?'No problem. We can continue without the NMI. Do you have a recent bill or smart-meter usage data?':(advancedQuestions[advancedFields.indexOf(nextField)]||`Please confirm your ${nextField}.`); const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${q}</p>`; transcript.appendChild(ai); saveTurn('assistant',q); window.speechSynthesis.speak(new SpeechSynthesisUtterance(q)); return; } const q='Do you consent to the privacy policy and contact for this test journey?'; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${q}</p>`; transcript.appendChild(ai); saveTurn('assistant',q); window.speechSynthesis.speak(new SpeechSynthesisUtterance(q)); journeyState='privacy'; return; }
  let a={next:'continue',safety:{}}; try{a=await fetch('http://localhost:8000/api/conversation/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lead_id:'EN-48219',text})}).then(r=>r.json())}catch(_){ }
  const lower=text.toLowerCase();
  if (/^(no|no thanks|no thank you|not interested|not now|i don't want to|i do not want to|dont want to)/.test(lower.trim())) { const reply="No problem, thanks for your time. I’ll record that you declined and end the call now."; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${reply}</p>`; transcript.appendChild(ai); saveTurn('assistant',reply); window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); if(browserRecognition) browserRecognition.stop(); journeyState='ended'; document.getElementById('statusText').textContent='Call ended · customer declined'; document.getElementById('nextActionValue').textContent='DO NOT CONTACT'; document.getElementById('nextActionDetail').textContent='Customer declined · no further questions'; showToast('Customer declined — call ended respectfully.'); return; }
  let reason=a.safety?.reason; if(!reason&&/stop calling|dont call|don't call|do not call|call me again|do not contact/.test(lower))reason='DNC request'; if(!reason&&/cheapest|recommend|best plan|advice/.test(lower))reason='Off-script request'; if(!reason&&/understand|confused|what do you mean|asking again/.test(lower))reason='Confusion / low confidence'; const needs=a.next==='handoff'||reason;
  if (!needs && journeyState==='consent' && /\b(yes|yeah|okay|ok|sure|continue)\b/.test(lower)) journeyState=activeLeadProfile.last_completed==='usage estimate'?'advanced':'postcode';
  const detectedPostcode = a.fields?.postcode || /^\d{4}$/.test(text.trim());
  if (!needs && journeyState==='postcode' && detectedPostcode) { journeyState='move_in_date'; document.getElementById('postcodeValue').textContent=detectedPostcode; document.getElementById('postcodeField').classList.remove('pending'); document.getElementById('postcodeField').querySelector('.field-dot').outerHTML='<span class="field-check">✓</span>'; document.getElementById('journeyCount').textContent='1 / 2'; document.getElementById('journeyProgress').style.width='50%'; }
  if (!needs && journeyState==='move_in_date' && !detectedPostcode && text.trim().length>0) { journeyState='nmi'; advancedIndex=0; document.getElementById('moveDateValue').textContent=text.trim(); document.getElementById('moveDateField').classList.remove('pending'); document.getElementById('moveDateField').querySelector('.field-dot').outerHTML='<span class="field-check">✓</span>'; document.getElementById('journeyCount').textContent='2 / 2'; document.getElementById('journeyProgress').style.width='100%'; document.getElementById('nextActionValue').textContent='CONTINUE CAPTURE'; document.getElementById('nextActionDetail').textContent='NMI and Energy profile still required'; document.getElementById('customerMeta').textContent='Lead EN-48219 · Energy comparison · Capturing Energy profile'; document.getElementById('statusText').textContent='Capturing profile'; }
  if (journeyState==='nmi') { const q=advancedQuestions[0]; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${q}</p>`; transcript.appendChild(ai); saveTurn('assistant',q); window.speechSynthesis.speak(new SpeechSynthesisUtterance(q)); return; }
  if (journeyState==='advanced' && activeLeadProfile.last_completed==='usage estimate' && advancedIndex===0) { const q='Do you have solar panels? If yes, what size?'; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${q}</p>`; transcript.appendChild(ai); saveTurn('assistant',q); window.speechSynthesis.speak(new SpeechSynthesisUtterance(q)); return; }
  const reply=needs?`I understand, and I’m sorry this has been frustrating. I’ll stop the automated call and connect you with a person now. You won’t need to repeat anything.`:journeyState==='consent'?`Thanks. Please say yes when you’re ready to continue, or say human if you would prefer a person.`:journeyState==='postcode'?`Thanks. What postcode should we use for the property?`:journeyState==='move_in_date'?`Thank you, I have your postcode. What is your move-in date for the property?`:`Thanks, I’ve captured that. The Energy journey is ready to submit.`; const ai=document.createElement('div'); ai.className='turn ai'; ai.innerHTML=`<span class="turn-label">AURALIS · NOW</span><p>${reply}</p>`; transcript.appendChild(ai); saveTurn('assistant', reply); transcript.scrollTop=transcript.scrollHeight; window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); if(needs){statePill.textContent='HANDOFF NOW';statePill.className='state-pill alert';signalValue.textContent=reason||'Safety signal detected';handoff.classList.add('alert');handoff.querySelector('strong').textContent='HUMAN HANDOFF REQUIRED';handoff.querySelector('p').textContent=`Reason: ${reason||'Safety signal detected'} · context attached`;showToast(`Escalating: ${reason||'Safety signal detected'}`)}
}
document.getElementById('sendChat').addEventListener('click',()=>{const i=document.getElementById('chatInput');sendChat(i.value);i.value=''}); document.getElementById('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('sendChat').click()}); document.querySelectorAll('.quick-examples button').forEach(b=>b.addEventListener('click',()=>sendChat(b.dataset.chat)));
document.getElementById('endBtn').addEventListener('click', () => { if(browserRecognition) browserRecognition.stop(); showToast('Call ended safely. Journey saved to review queue.'); });
document.addEventListener('click', e => { const lead=e.target.closest('.lead'); if(lead){ activeLeadId=lead.dataset.id; activeLeadProfile=leadProfiles[lead.dataset.id]||{last_completed:lead.dataset.drop||'postcode',intent:'Energy comparison',missing:[lead.dataset.drop||'next field'],consent:true}; } });
document.addEventListener('click', e => { const lead=e.target.closest('.lead'); if(!lead) return; document.getElementById('customerName').innerHTML=`${lead.dataset.name} <span class="verified">✓</span>`; transcript.innerHTML='<div class="empty-transcript">Click <strong>Start call</strong> to begin this lead\'s recovery conversation.</div>'; statePill.textContent='ON TRACK'; statePill.className='state-pill good'; signalValue.textContent='Awaiting conversation'; handoff.classList.remove('alert'); handoff.querySelector('strong').textContent='HUMAN HANDOFF READY'; handoff.querySelector('p').textContent='When things turn, context moves with the call.'; document.getElementById('statusText').textContent='Ready'; document.getElementById('customerMeta').textContent=`Lead ${lead.dataset.id} · Energy comparison · Awaiting consent`; });
document.addEventListener('click', e => { const lead=e.target.closest('.lead'); if(lead) advancedIndex=0; });
const notes=document.getElementById('callNotes'); const notesKey=()=>`auralis-notes-${activeLeadId}`; notes.value=localStorage.getItem(notesKey())||''; notes.addEventListener('input',()=>localStorage.setItem(notesKey(),notes.value)); document.querySelectorAll('.notes-tags button').forEach(b=>b.addEventListener('click',()=>{notes.value+=(notes.value?'\n':'')+b.dataset.note; notes.focus(); notes.dispatchEvent(new Event('input'));}));
document.querySelectorAll('.judge-buttons button').forEach(b => b.addEventListener('click', () => sendChat(b.dataset.chat)));
document.getElementById('submitJourney').addEventListener('click',()=>{const nmi=document.getElementById('nmi').value.trim(), usage=document.getElementById('usage').value, consent=document.getElementById('privacyConsent').checked; if(!/^\d{11}$/.test(nmi)){showToast('Enter a test NMI with 11 digits');return} if(!usage){showToast('Select a usage source');return} if(!consent){showToast('Consent is required before submission');return} const savings=Math.floor(420+Math.random()*280); document.getElementById('savingsResult').innerHTML=`<strong>JOURNEY RECOVERED</strong><span>Estimated annual saving against reference price: <b>$${savings}</b></span><small>Test payload accepted · DMO/VDO comparison simulated · no product advice given</small>`; document.getElementById('nextActionValue').textContent='RECOVERED'; document.getElementById('nextActionDetail').textContent='All Energy fields captured · sandbox payload accepted'; document.getElementById('statusText').textContent='Journey submitted'; journeyState='complete'; showToast('Energy journey submitted successfully');});
document.addEventListener('click', e => { const lead=e.target.closest('.lead'); if(!lead) return; journeyState='consent'; escalated=false; consented=false; document.getElementById('journeyCount').textContent='0 / 2'; document.getElementById('postcodeValue').textContent='Awaiting'; document.getElementById('postcodeField').classList.add('pending'); document.getElementById('postcodeField').querySelector('.field-check')?.replaceWith(Object.assign(document.createElement('span'),{className:'field-dot'})); document.getElementById('moveDateValue').textContent='Awaiting'; document.getElementById('moveDateField').classList.add('pending'); document.getElementById('journeyProgress').style.width='0%'; document.getElementById('customerMeta').textContent=`Lead ${lead.dataset.id} · Energy comparison · Awaiting consent`; });
let recorder, chunks = [];
document.getElementById('micBtn').addEventListener('click', async () => {
  const button = document.getElementById('micBtn');
  if (!navigator.mediaDevices?.getUserMedia) { showToast('Microphone is not available in this browser.'); return; }
  if (recorder?.state === 'recording') { recorder.stop(); return; }
  try {
    const stream = await navigator.mediaDevices.getUserMedia({audio:true});
    chunks = []; recorder = new MediaRecorder(stream); recorder.ondataavailable = e => chunks.push(e.data);
    recorder.onstop = async () => {
      stream.getTracks().forEach(t => t.stop()); button.innerHTML = '<span>◉</span> Listening automatically';
      const blob = new Blob(chunks, {type:'audio/webm'}); const form = new FormData(); form.append('audio', blob, 'turn.webm');
      showToast('Transcribing with Faster-Whisper…');
      try {
        const res = await fetch('http://localhost:8000/api/speech/transcribe', {method:'POST', body:form});
        const data = await res.json(); if (!data.text) throw new Error('No speech detected');
        const turn = document.createElement('div'); turn.className = 'turn customer'; turn.innerHTML = `<span class="turn-label">YOU · NOW</span><p class="highlight">${data.text}</p>`; transcript.appendChild(turn);
        const analysis = await fetch('http://localhost:8000/api/conversation/analyse', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lead_id:'EN-48219',text:data.text})}).then(r=>r.json());
        const reply = analysis.next === 'handoff' ? "I hear you. I will stop the automated call and connect you with a person. You will not need to repeat your details." : (analysis.next === 'move_in_date' ? "Thank you, I have your postcode. What is your move in date for the property?" : "Thanks. What postcode should we use for the property?");
        const ai = document.createElement('div'); ai.className = 'turn ai'; ai.innerHTML = `<span class="turn-label">AURALIS · NOW</span><p>${reply}</p>`; transcript.appendChild(ai); transcript.scrollTop = transcript.scrollHeight;
        // Piper is used when available; browser speech keeps the demo audible without setup.
        try { const audio = await fetch('http://localhost:8000/api/speech/synthesize', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:reply})}); if (audio.ok) { const info = await audio.json(); if (info.audio_url) new Audio(info.audio_url).play(); else window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); } else throw new Error('Piper unavailable'); } catch (_) { window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)); }
        if (analysis.next === 'handoff') runFrustration(); else showToast('Auralis replied — listen for the next Energy question.');
      } catch (e) { showToast('Speech service unavailable — use the scenario button for the demo.'); }
    };
    recorder.start(); button.innerHTML = '<span>■</span> Stop recording'; statusText.textContent = 'Listening to caller'; showToast('Listening… speak naturally, then press again to stop.');
  } catch (e) { showToast('Microphone permission was not granted.'); }
});
